# Generated by Django 6.0.5 on 2026-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
