# Generated by Django 6.0.5 on 2026-05-22 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicinereminder_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='hrv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='irregular_hr_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='sitting_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='snoring_events',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='spo2_drops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='stress_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskprediction',
            name='disease_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_reports/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
