# Generated by Django 6.0.5 on 2026-06-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_medicalreport_metric_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='image',
            field=models.FileField(upload_to='medical_reports/'),
        ),
    ]
